services:
  db:
    image: mysql:8
    container_name: hotel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel
      MYSQL_USER: hoteluser
      MYSQL_PASSWORD: hotelpass
    ports:
      - "3307:3306"   
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./apps/backend
    container_name: hotel-backend
    restart: always
    ports:
      - "4000:4000"  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hotel-network

  frontend:
    build: ./apps/frontend
    container_name: hotel-frontend
    restart: always
    ports:
      - "3000:80"   
    depends_on:
      - backend
    networks:
      - hotel-network

  nginx:
    image: nginx:latest
    container_name: hotel-nginx
    restart: always
    ports:
      - "8080:80"   
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - hotel-network

volumes:
  db-data:

networks:
  hotel-network:
    driver: bridge
