version: "3.9"

services:
  backend:
    build:
      context: .            
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app      

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app      
